import Head from "next/head";
import { PrimaryButton } from "../src/components/small/primarybtn/PrimaryBtn";
import { useFetch, usePost } from "../src/utils/Hooks";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rent-a-thing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
